module.exports = {
    createCircuitsTable: `CREATE TABLE circuits(
        circuitId integer NOT NULL PRIMARY KEY,
        circuitRef VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        location VARCHAR(255) NOT NULL,
        country VARCHAR(255) NOT NULL,
        lat float NOT NULL,
        lng float NOT NULL,
        alt float NOT NULL,
        url VARCHAR(255) NOT NULL);`,
    createConstructorResultsTable: `CREATE TABLE constructor_results(
        constructorResultsId integer NOT NULL PRIMARY KEY,
        raceId integer NOT NULL,
        constructorId integer NOT NULL,
        points float NOT NULL,
        status VARCHAR(255) NOT NULL);`,
    createConstructorStandingsTable: `CREATE TABLE constructor_standings(
        constructorStandingsId integer NOT NULL PRIMARY KEY,
        raceId integer NOT NULL,
        constructorId integer NOT NULL,
        points float NOT NULL,
        position integer NOT NULL,
        positionText VARCHAR(255) NOT NULL,
        wins integer NOT NULL);`,
    createConstructorsTable: `CREATE TABLE constructors(
        constructorId integer NOT NULL PRIMARY KEY,
        constructorRef VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL,
        nationality VARCHAR(255) NOT NULL,
        url VARCHAR(255) NOT NULL);`,
    createDriverStandingsTable: `CREATE TABLE driver_standings(
        driverStandingsId integer NOT NULL PRIMARY KEY,
        raceId integer NOT NULL,
        driverId integer NOT NULL,
        points float NOT NULL,
        position integer NOT NULL,
        positionText VARCHAR(255) NOT NULL,
        wins integer NOT NULL);`,
    createDriversTable: `CREATE TABLE drivers(
        driverId integer NOT NULL PRIMARY KEY,
        driverRef VARCHAR(255) NOT NULL,
        number VARCHAR(255) NOT NULL ,
        code VARCHAR(255) ,
        forename VARCHAR(255) NOT NULL,
        surname VARCHAR(255) NOT NULL,
        dob VARCHAR(255) NOT NULL,
        nationality VARCHAR(255) NOT NULL,
        url VARCHAR(255) NOT NULL);`,
    createLapTimesTable: `CREATE TABLE lap_times(
        raceId integer NOT NULL ,
        driverId integer NOT NULL,
        lap integer NOT NULL ,
        position integer NOT NULL ,
        time time NOT NULL,
        milliseconds integer NOT NULL);`,
    createPitStopsTable: `CREATE TABLE pit_stops(
        raceId integer NOT NULL,
        driverId integer NOT NULL,
        stop integer NOT NULL,
        lap integer NOT NULL,
        time VARCHAR(255) NOT NULL,
        duration VARCHAR(255) NOT NULL,
        milliseconds integer NOT NULL);`,
    createQualifyingTable: `CREATE TABLE qualifying(
        qualifyId integer NOT NULL PRIMARY KEY,
        raceId integer NOT NULL, 
        driverId integer NOT NULL,
        constructorId integer NOT NULL,
        number integer NOT NULL,
        position integer NOT NULL,
        q1 VARCHAR(255) NOT NULL,
        q2 VARCHAR(255) NOT NULL,
        q3 VARCHAR(255) NOT NULL);`,
    createRacesTable: `CREATE TABLE races(
        raceId integer NOT NULL PRIMARY KEY,
        year integer NOT NULL,
        round integer NOT NULL,
        circuitId integer NOT NULL,
        name VARCHAR(255) NOT NULL,
        date VARCHAR(255) NOT NULL,
        time VARCHAR(255) NOT NULL,
        url VARCHAR(255) NOT NULL);`,
    createResultsTable: `CREATE TABLE results(
        resultId integer NOT NULL PRIMARY KEY,
        raceId integer NOT NULL,
        driverId integer NOT NULL ,
        constructorId integer NOT NULL,
        number VARCHAR(255) NOT NULL,
        grid integer NOT NULL,
        position VARCHAR(255) NOT NULL,
        positionText VARCHAR(255) NOT NULL,
        positionOrder integer NOT NULL,
        points float NOT NULL,
        laps integer NOT NULL,
        time VARCHAR(255) NOT NULL,
        milliseconds VARCHAR(255) NOT NULL,
        fastestLap VARCHAR(255) NOT NULL,
        rank VARCHAR(255) NOT NULL,
        fastestLapTime VARCHAR(255) NOT NULL,
        fastestLapSpeed VARCHAR(255) NOT NULL,
        statusId integer NOT NULL);`,
    createSeasonsTable: `CREATE TABLE seasons(
        year integer NOT NULL,
        url VARCHAR(255) NOT NULL);`,
    createStatusTable: `CREATE TABLE status(
        statusId integer NOT NULL PRIMARY KEY,
        status VARCHAR(255) NOT NULL);`,
}